[platformio]
src_dir = .

[env:upesy_wrover]
platform = espressif32
board = upesy_wrover
framework = arduino
monitor_speed = 115200
lib_deps =
    adafruit/Adafruit BME280 Library @ 2.3.0
    adafruit/Adafruit Unified Sensor @ 1.1.15
    adafruit/RTClib @ 2.1.4
    mathieucarbou/ESPAsyncWebServer @ 3.1.5
