project:
  type: book
  output-dir: _output

book:
  title: "PAWS"
  subtitle: "Personal Autonomous Weather Station"
  repo-url: https://github.com/wg1d/personal-autonomous-weather-station
  repo-branch: main
  date: last-modified
  reader-mode: false

  chapters:
    - index.qmd
    - chapters/01-motivation.qmd
    - chapters/02-roadmap.qmd
    - chapters/03-architecture.qmd

format:
  html:
    theme: cosmo
    fig-align: center
    toc: true
    toc-depth: 3
    number-sections: true
    number-depth: 3
    highlight-style: github
    code-fold: false
    html-math-method: katex
    smooth-scroll: true
    mermaid:
      theme: neutral
