project:
  type: book
  output-dir: _output

book:
  title: "PAWS"
  subtitle: "Personal Autonomous Weather Station"
  repo-url: https://github.com/wg1d/personal-autonomous-weather-station
  repo-branch: main
  date: last-modified
  reader-mode: false

  chapters:
    - index.qmd
    - chapters/01-motivation.qmd
    - chapters/02-roadmap.qmd
    - part: "PoC - Phase 1: Core Functionality"
      chapters:
        - chapters/PoC/Phase-01/01-components.qmd
        - chapters/PoC/Phase-01/02-data-acquisition.qmd
        - chapters/PoC/Phase-01/03-data-storage.qmd
        - chapters/PoC/Phase-01/04-real-time-clock.qmd
    - part: "PoC - Phase 2: Power Management"
      chapters:
        - chapters/PoC/Phase-02/01-deep-sleep.qmd
        - chapters/PoC/Phase-02/02-hardware-modifications.qmd
        - chapters/PoC/Phase-02/03-software-implementation.qmd
    - part: "PoC - Phase 3: Wi-Fi & Data Transmission"
      chapters:
        - chapters/PoC/Phase-03/01-wifi-station.qmd
        - chapters/PoC/Phase-03/02-dummy-backend.qmd
        - chapters/PoC/Phase-03/03-fallback-ap.qmd
        - chapters/PoC/Phase-03/04-ntp-sync.qmd
    - part: "Production - Phase 4: Modular Architecture"
      chapters:
        - chapters/Architecture/Phase-04/01-fsm-skeleton.qmd
        - chapters/Architecture/Phase-04/02-sensor-and-storage.qmd
        - chapters/Architecture/Phase-04/03-network-and-time.qmd

format:
  html:
    theme:
      - cosmo
      - custom.scss
    fig-align: center
    toc: true
    toc-depth: 4
    number-sections: true
    number-depth: 4
    highlight-style: github
    code-fold: false
    html-math-method: katex
    smooth-scroll: true
    mermaid:
      theme: neutral
